version: '3'
services:
  rabbitmq:
    container_name: rabbitmq
    build:
      context: .
      dockerfile: ./rabbitmq/rabbitmq.dockerfile
    ports:
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
    restart: on-failure
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    networks:
      - local_net

  stations-manager:
    container_name: stations-manager
    build:
      context: .
      dockerfile: ./backend/stations_manager/stations-manager.dockerfile
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_HOSTNAME=${RABBITMQ_HOSTNAME}
      - N_MONTREAL_STATIONS_JOINERS=${N_MONTREAL_STATIONS_JOINERS}
      - SUPERVISOR_NODE_ID=1
      - SUPERVISOR_EXCHANGE_NAME=${SUPERVISOR_EXCHANGE_NAME}
      - SUPERVISOR_NETWORK_SIZE=${SUPERVISOR_NETWORK_SIZE}
      - SUPERVISOR_NODE_ID_TO_CONTAINER_NAME_MAPPING=${SUPERVISOR_NODE_ID_TO_CONTAINER_NAME_MAPPING}
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend/stations_manager/.storage:/.storage
      - ./backend/stations_manager/.eof:/.eof
      - ./backend/stations_manager/.clients:/.clients
    networks:
      - local_net

  weather-manager:
    container_name: weather-manager
    build:
      context: .
      dockerfile: ./backend/weather_manager/weather_manager.dockerfile
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_HOSTNAME=${RABBITMQ_HOSTNAME}
      - SUPERVISOR_NODE_ID=2
      - SUPERVISOR_EXCHANGE_NAME=${SUPERVISOR_EXCHANGE_NAME}
      - SUPERVISOR_NETWORK_SIZE=${SUPERVISOR_NETWORK_SIZE}
      - SUPERVISOR_NODE_ID_TO_CONTAINER_NAME_MAPPING=${SUPERVISOR_NODE_ID_TO_CONTAINER_NAME_MAPPING}
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend/weather_manager/.storage:/.storage
      - ./backend/weather_manager/.eof:/.eof
      - ./backend/weather_manager/.clients:/.clients
    networks:
      - local_net

  trip-duration-running-avg:
    container_name: trip-duration-running-avg
    build:
      context: .
      dockerfile: backend/trip_duration_running_avg/trip_duration_running_avg.dockerfile
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_HOSTNAME=${RABBITMQ_HOSTNAME}
      - SUPERVISOR_NODE_ID=3
      - SUPERVISOR_EXCHANGE_NAME=${SUPERVISOR_EXCHANGE_NAME}
      - SUPERVISOR_NETWORK_SIZE=${SUPERVISOR_NETWORK_SIZE}
      - SUPERVISOR_NODE_ID_TO_CONTAINER_NAME_MAPPING=${SUPERVISOR_NODE_ID_TO_CONTAINER_NAME_MAPPING}
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend/trip_duration_running_avg/.storage:/.storage
      - ./backend/trip_duration_running_avg/.eof:/.eof
      - ./backend/trip_duration_running_avg/.clients:/.clients
    networks:
      - local_net

  by-station-yearly-trips-count:
    container_name: by-station-yearly-trips-count
    build:
      context: .
      dockerfile: ./backend/by_year_and_station_trips_count/by_year_and_station_trips_count.dockerfile
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
      - stations-manager
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_HOSTNAME=${RABBITMQ_HOSTNAME}
      - N_BY_YEAR_TRIPS_FILTERS=${N_BY_YEAR_TRIPS_FILTERS}
      - SUPERVISOR_NODE_ID=4
      - SUPERVISOR_EXCHANGE_NAME=${SUPERVISOR_EXCHANGE_NAME}
      - SUPERVISOR_NETWORK_SIZE=${SUPERVISOR_NETWORK_SIZE}
      - SUPERVISOR_NODE_ID_TO_CONTAINER_NAME_MAPPING=${SUPERVISOR_NODE_ID_TO_CONTAINER_NAME_MAPPING}
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend/by_year_and_station_trips_count/.storage:/.storage
      - ./backend/by_year_and_station_trips_count/.eof:/.eof
      - ./backend/by_year_and_station_trips_count/.clients:/.clients
    networks:
      - local_net

  by-year-trips-filter-1:
    container_name: by-year-trips-filter-1
    build:
      context: .
      dockerfile: ./backend/by_year_trips_filter/by_year_trips_filter.dockerfile
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
      - by-station-yearly-trips-count
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_HOSTNAME=${RABBITMQ_HOSTNAME}
      - SUPERVISOR_NODE_ID=5
      - SUPERVISOR_EXCHANGE_NAME=${SUPERVISOR_EXCHANGE_NAME}
      - SUPERVISOR_NETWORK_SIZE=${SUPERVISOR_NETWORK_SIZE}
      - SUPERVISOR_NODE_ID_TO_CONTAINER_NAME_MAPPING=${SUPERVISOR_NODE_ID_TO_CONTAINER_NAME_MAPPING}
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend/by_year_trips_filter/.eof:/.eof
    networks:
      - local_net

  weather-filter-1:
    container_name: weather-filter-1
    build:
      context: .
      dockerfile: ./backend/weather_filter/weather_filter.dockerfile
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
      - weather-manager
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_HOSTNAME=${RABBITMQ_HOSTNAME}
      - SUPERVISOR_NODE_ID=6
      - SUPERVISOR_EXCHANGE_NAME=${SUPERVISOR_EXCHANGE_NAME}
      - SUPERVISOR_NETWORK_SIZE=${SUPERVISOR_NETWORK_SIZE}
      - SUPERVISOR_NODE_ID_TO_CONTAINER_NAME_MAPPING=${SUPERVISOR_NODE_ID_TO_CONTAINER_NAME_MAPPING}
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend/weather_filter/.eof_1:/.eof
    networks:
      - local_net

  stations-distance-running-avg:
    container_name: stations-distance-running-avg
    build:
      context: .
      dockerfile: ./backend/stations_distance_running_avg/stations_distance_running_avg.dockerfile
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_HOSTNAME=${RABBITMQ_HOSTNAME}
      - N_DISTANCE_CALCULATORS=${N_DISTANCE_CALCULATORS}
      - SUPERVISOR_NODE_ID=7
      - SUPERVISOR_EXCHANGE_NAME=${SUPERVISOR_EXCHANGE_NAME}
      - SUPERVISOR_NETWORK_SIZE=${SUPERVISOR_NETWORK_SIZE}
      - SUPERVISOR_NODE_ID_TO_CONTAINER_NAME_MAPPING=${SUPERVISOR_NODE_ID_TO_CONTAINER_NAME_MAPPING}
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend/stations_distance_running_avg/.storage:/.storage
      - ./backend/stations_distance_running_avg/.eof:/.eof
      - ./backend/stations_distance_running_avg/.clients:/.clients
    networks:
      - local_net

  distance-calculator-1:
    container_name: distance-calculator-1
    build:
      context: .
      dockerfile: ./backend/distance_calculator/distance_calculator.dockerfile
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - stations-distance-running-avg
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_HOSTNAME=${RABBITMQ_HOSTNAME}
      - N_MONTREAL_STATIONS_JOINERS=${N_MONTREAL_STATIONS_JOINERS}
      - SUPERVISOR_NODE_ID=8
      - SUPERVISOR_EXCHANGE_NAME=${SUPERVISOR_EXCHANGE_NAME}
      - SUPERVISOR_NETWORK_SIZE=${SUPERVISOR_NETWORK_SIZE}
      - SUPERVISOR_NODE_ID_TO_CONTAINER_NAME_MAPPING=${SUPERVISOR_NODE_ID_TO_CONTAINER_NAME_MAPPING}
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend/distance_calculator/.eof_1:/.eof
    networks:
      - local_net

  distance-calculator-2:
    container_name: distance-calculator-2
    build:
      context: .
      dockerfile: ./backend/distance_calculator/distance_calculator.dockerfile
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - stations-distance-running-avg
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_HOSTNAME=${RABBITMQ_HOSTNAME}
      - N_MONTREAL_STATIONS_JOINERS=${N_MONTREAL_STATIONS_JOINERS}
      - SUPERVISOR_NODE_ID=9
      - SUPERVISOR_EXCHANGE_NAME=${SUPERVISOR_EXCHANGE_NAME}
      - SUPERVISOR_NETWORK_SIZE=${SUPERVISOR_NETWORK_SIZE}
      - SUPERVISOR_NODE_ID_TO_CONTAINER_NAME_MAPPING=${SUPERVISOR_NODE_ID_TO_CONTAINER_NAME_MAPPING}
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend/distance_calculator/.eof_2:/.eof
    networks:
      - local_net

  montreal-stations-joiner-1:
    container_name: montreal-stations-joiner-1
    build:
      context: .
      dockerfile: backend/montreal_stations_joiner/montreal_stations_joiner.dockerfile
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - distance-calculator-1
      - distance-calculator-2
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_HOSTNAME=${RABBITMQ_HOSTNAME}
      - N_DISTANCE_CALCULATORS=${N_DISTANCE_CALCULATORS}
      - SUPERVISOR_NODE_ID=10
      - SUPERVISOR_EXCHANGE_NAME=${SUPERVISOR_EXCHANGE_NAME}
      - SUPERVISOR_NETWORK_SIZE=${SUPERVISOR_NETWORK_SIZE}
      - SUPERVISOR_NODE_ID_TO_CONTAINER_NAME_MAPPING=${SUPERVISOR_NODE_ID_TO_CONTAINER_NAME_MAPPING}
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend/montreal_stations_joiner/.eof_1:/.eof
    networks:
      - local_net

  montreal-stations-joiner-2:
    container_name: montreal-stations-joiner-2
    build:
      context: .
      dockerfile: backend/montreal_stations_joiner/montreal_stations_joiner.dockerfile
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - distance-calculator-1
      - distance-calculator-2
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_HOSTNAME=${RABBITMQ_HOSTNAME}
      - N_DISTANCE_CALCULATORS=${N_DISTANCE_CALCULATORS}
      - SUPERVISOR_NODE_ID=11
      - SUPERVISOR_EXCHANGE_NAME=${SUPERVISOR_EXCHANGE_NAME}
      - SUPERVISOR_NETWORK_SIZE=${SUPERVISOR_NETWORK_SIZE}
      - SUPERVISOR_NODE_ID_TO_CONTAINER_NAME_MAPPING=${SUPERVISOR_NODE_ID_TO_CONTAINER_NAME_MAPPING}
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend/montreal_stations_joiner/.eof_2:/.eof
    networks:
      - local_net

  montreal-stations-over-6km-avg-trip-distance-ingestor:
    container_name: montreal-distance-trips-ingestor
    build:
      context: .
      dockerfile: ./backend/montreal_stations_over_6km_avg_trip_distance_ingestor/Dockerfile
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
      - stations-manager
      - montreal-stations-joiner-1
      - montreal-stations-joiner-2
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_HOSTNAME=${RABBITMQ_HOSTNAME}
      - N_STATIONS_JOINERS=${N_MONTREAL_STATIONS_JOINERS}
      - SUPERVISOR_NODE_ID=12
      - SUPERVISOR_EXCHANGE_NAME=${SUPERVISOR_EXCHANGE_NAME}
      - SUPERVISOR_NETWORK_SIZE=${SUPERVISOR_NETWORK_SIZE}
      - SUPERVISOR_NODE_ID_TO_CONTAINER_NAME_MAPPING=${SUPERVISOR_NODE_ID_TO_CONTAINER_NAME_MAPPING}
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend/montreal_stations_over_6km_avg_trip_distance_ingestor/.eof:/.eof
    networks:
      - local_net

  doubled-yearly-trips-stations-ingestor:
    container_name: doubled-yearly-trips-stations-ingestor
    build:
      context: .
      dockerfile: ./backend/doubled_yearly_trips_stations_ingestor/Dockerfile
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
      - by-year-trips-filter-1
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_HOSTNAME=${RABBITMQ_HOSTNAME}
      - N_BY_YEAR_TRIPS_FILTERS=${N_BY_YEAR_TRIPS_FILTERS}
      - SUPERVISOR_NODE_ID=13
      - SUPERVISOR_EXCHANGE_NAME=${SUPERVISOR_EXCHANGE_NAME}
      - SUPERVISOR_NETWORK_SIZE=${SUPERVISOR_NETWORK_SIZE}
      - SUPERVISOR_NODE_ID_TO_CONTAINER_NAME_MAPPING=${SUPERVISOR_NODE_ID_TO_CONTAINER_NAME_MAPPING}
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend/doubled_yearly_trips_stations_ingestor/.eof:/.eof
    networks:
      - local_net

  with-precipitations-avg-duration-trip-ingestor:
    container_name: with-precipitations-avg-duration-trip-ingestor
    build:
      context: .
      dockerfile: ./backend/with_precipitations_avg_duration_trip_ingestor/Dockerfile
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
      - weather-manager
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_HOSTNAME=${RABBITMQ_HOSTNAME}
      - SUPERVISOR_NODE_ID=14
      - SUPERVISOR_EXCHANGE_NAME=${SUPERVISOR_EXCHANGE_NAME}
      - SUPERVISOR_NETWORK_SIZE=${SUPERVISOR_NETWORK_SIZE}
      - SUPERVISOR_NODE_ID_TO_CONTAINER_NAME_MAPPING=${SUPERVISOR_NODE_ID_TO_CONTAINER_NAME_MAPPING}
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend/with_precipitations_avg_duration_trip_ingestor/.eof:/.eof
    networks:
      - local_net

  data-ingestion-server:
    container_name: data-ingestion-server
    build:
      context: .
      dockerfile: backend/data_ingestion_server/data_ingestion_server.dockerfile
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
      - stations-manager
      - weather-filter-1
      - montreal-stations-over-6km-avg-trip-distance-ingestor
      - stations-distance-running-avg
      - by-station-yearly-trips-count
      - doubled-yearly-trips-stations-ingestor
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_HOSTNAME=${RABBITMQ_HOSTNAME}
      - STATIONS_EXCHANGE_NAME=stations_exchange
    networks:
      - local_net

  client:
    build:
      context: .
      dockerfile: ./frontend/client.dockerfile
    restart: on-failure
    depends_on:
       - data-ingestion-server
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_HOSTNAME=${RABBITMQ_HOSTNAME}
      - DATA_PATH=data
    networks:
      - local_net
    volumes:
      - ./.data:/data
      - results:/results

networks:
  local_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.127.0/24

volumes:
  client:
  results:
